name: Build and test
on:
  push:
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
      - ".gitignore"
      - ".gitattributes"
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
      - ".gitignore"
      - ".gitattributes"
    branches:
      - "*"
    tags-ignore:
      - "*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - uses: robherley/go-test-action@v0.1.0
        with:
          omit: |
            pie
            untested
